[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "cryptocore"
version = "0.2.0"
description = "AES-128 ECB file encryption and decryption CLI"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "pycryptodome>=3.20,<4",
]


[project.optional-dependencies]
dev = [
    "pytest>=8,<9",
]


[project.scripts]
cryptocore = "cryptocore.cli:main"


[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]


[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]